version: '3.9'

services:

  nginx:
    container_name: laravel-10-nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  db:
    container_name: laravel-10-database
    image: mysql:latest
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  app:
    container_name: laravel-10-app
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

  phpmyadmin:
    container_name: laravel-10-phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8888:80
    depends_on:
      - db